export const categories = [
  {
    id: 4,
    name: 'كروت وأرصدة ألعاب',
    name_en: 'Game Cards & Credits',
    slug: 'game-cards',
    emoji: '🎮💳',
    gradient: 'from-purple-500 to-indigo-400',
  },
  {
    id: 5,
    name: 'اشتراكات رقمية',
    name_en: 'Digital Subscriptions',
    slug: 'subscriptions',
    emoji: '📺🎧',
    gradient: 'from-sky-500 to-cyan-300',
  },
  {
    id: 6,
    name: 'أرصدة واتصالات',
    name_en: 'Mobile Balance',
    slug: 'mobile-balance',
    emoji: '📱⚡',
    gradient: 'from-rose-500 to-pink-300',
  },
  {
    id: 7,
    name: 'قسائم هدايا',
    name_en: 'Gift Cards',
    slug: 'gift-cards',
    emoji: '🎁🛍️',
    gradient: 'from-orange-500 to-amber-300',
  },
  {
    id: 8,
    name: 'برامج وخدمات',
    name_en: 'Software & Services',
    slug: 'software-services',
    emoji: '💻🔐',
    gradient: 'from-stone-700 to-stone-400',
  },
  {
    id: 9,
    name: 'متاجر عالمية',
    name_en: 'Global Stores',
    slug: 'global-stores',
    emoji: '🌍🛒',
    gradient: 'from-blue-500 to-indigo-300',
  },
  {
    id: 10,
    name: 'بطاقات ترفيه',
    name_en: 'Entertainment Cards',
    slug: 'entertainment-cards',
    emoji: '🎬🍿',
    gradient: 'from-red-500 to-rose-300',
  },
  {
    id: 11,
    name: 'تعليم وإنتاجية',
    name_en: 'Learning & Productivity',
    slug: 'learning-productivity',
    emoji: '📚⚙️',
    gradient: 'from-teal-500 to-emerald-300',
  },
];

export const products = [
  {
    id: 401,
    category_id: 4,
    name: 'بطاقة PlayStation Store 10$',
    name_en: 'PlayStation Store Card $10',
    description: 'كود رقمي لشحن رصيد PlayStation Store.',
    description_en: 'Digital code for PlayStation Store balance.',
    price: 40,
    unit: 'code',
    stock: 50,
    badge: 'رقمي',
  },
  {
    id: 402,
    category_id: 4,
    name: 'بطاقة Xbox Gift Card 15$',
    name_en: 'Xbox Gift Card $15',
    description: 'كود رقمي لحساب Xbox أو Microsoft.',
    description_en: 'Digital code for Xbox or Microsoft accounts.',
    price: 58,
    unit: 'code',
    stock: 35,
  },
  {
    id: 403,
    category_id: 4,
    name: 'شدات PUBG Mobile',
    name_en: 'PUBG Mobile UC',
    description: 'رصيد UC رقمي لحساب PUBG Mobile.',
    description_en: 'Digital UC balance for PUBG Mobile.',
    price: 22,
    unit: 'pack',
    stock: 40,
  },
  {
    id: 501,
    category_id: 5,
    name: 'اشتراك Netflix شهر',
    name_en: 'Netflix Subscription 1 Month',
    description: 'اشتراك رقمي لمدة شهر واحد.',
    description_en: 'Digital subscription for one month.',
    price: 35,
    unit: 'month',
    stock: 15,
    badge: 'عرض',
  },
  {
    id: 502,
    category_id: 5,
    name: 'اشتراك Spotify شهر',
    name_en: 'Spotify Subscription 1 Month',
    description: 'اشتراك Spotify Premium لمدة شهر.',
    description_en: 'Spotify Premium subscription for one month.',
    price: 25,
    unit: 'month',
    stock: 25,
  },
  {
    id: 601,
    category_id: 6,
    name: 'رصيد جوال 20 شيكل',
    name_en: 'Mobile Balance 20 ILS',
    description: 'رصيد رقمي لشحن خط الجوال.',
    description_en: 'Digital top-up for mobile lines.',
    price: 20,
    unit: 'top-up',
    stock: 60,
  },
  {
    id: 602,
    category_id: 6,
    name: 'رصيد جوال 50 شيكل',
    name_en: 'Mobile Balance 50 ILS',
    description: 'رصيد رقمي بقيمة 50 شيكل.',
    description_en: 'Digital top-up worth 50 ILS.',
    price: 50,
    unit: 'top-up',
    stock: 60,
  },
  {
    id: 701,
    category_id: 7,
    name: 'بطاقة Amazon 25$',
    name_en: 'Amazon Gift Card $25',
    description: 'كود هدية رقمي للاستخدام على Amazon.',
    description_en: 'Digital gift code for Amazon.',
    price: 98,
    unit: 'code',
    stock: 20,
  },
  {
    id: 702,
    category_id: 7,
    name: 'بطاقة Apple Gift Card 10$',
    name_en: 'Apple Gift Card $10',
    description: 'كود رقمي لحساب Apple.',
    description_en: 'Digital code for Apple accounts.',
    price: 40,
    unit: 'code',
    stock: 30,
  },
  {
    id: 801,
    category_id: 8,
    name: 'مفتاح Microsoft 365',
    name_en: 'Microsoft 365 Key',
    description: 'مفتاح رقمي لخدمة Microsoft 365.',
    description_en: 'Digital key for Microsoft 365.',
    price: 75,
    unit: 'key',
    stock: 12,
  },
  {
    id: 802,
    category_id: 8,
    name: 'VPN شهر واحد',
    name_en: 'VPN 1 Month',
    description: 'اشتراك VPN رقمي لمدة شهر.',
    description_en: 'Digital VPN subscription for one month.',
    price: 18,
    unit: 'month',
    stock: 0,
  },
  {
    id: 901,
    category_id: 9,
    name: 'بطاقة Steam 20$',
    name_en: 'Steam Wallet Card $20',
    description: 'كود رقمي لمحفظة Steam.',
    description_en: 'Digital wallet code for Steam.',
    price: 78,
    unit: 'code',
    stock: 25,
  },
  {
    id: 902,
    category_id: 9,
    name: 'بطاقة Google Play 10$',
    name_en: 'Google Play Gift Card $10',
    description: 'كود رقمي لمتجر Google Play.',
    description_en: 'Digital code for Google Play.',
    price: 40,
    unit: 'code',
    stock: 30,
  },
  {
    id: 1001,
    category_id: 10,
    name: 'اشتراك Shahid شهر',
    name_en: 'Shahid Subscription 1 Month',
    description: 'اشتراك رقمي لخدمة شاهد لمدة شهر.',
    description_en: 'Digital Shahid subscription for one month.',
    price: 28,
    unit: 'month',
    stock: 18,
  },
  {
    id: 1002,
    category_id: 10,
    name: 'بطاقة TOD شهر',
    name_en: 'TOD Subscription 1 Month',
    description: 'اشتراك رقمي لخدمة TOD لمدة شهر.',
    description_en: 'Digital TOD subscription for one month.',
    price: 32,
    unit: 'month',
    stock: 16,
  },
  {
    id: 1101,
    category_id: 11,
    name: 'اشتراك Canva Pro شهر',
    name_en: 'Canva Pro 1 Month',
    description: 'اشتراك Canva Pro رقمي لمدة شهر.',
    description_en: 'Digital Canva Pro subscription for one month.',
    price: 24,
    unit: 'month',
    stock: 20,
  },
  {
    id: 1102,
    category_id: 11,
    name: 'رصيد Udemy Course',
    name_en: 'Udemy Course Credit',
    description: 'رصيد رقمي لشراء دورة تعليمية.',
    description_en: 'Digital credit for an online course.',
    price: 45,
    unit: 'credit',
    stock: 10,
  },
];
